46 Crash when writing cache on invalid state fixed
opentap/Parquet pull request #47
Opened 2024-03-15 08:50 UTC by frederikja163

Closes #46

2024-03-15 08:51 UTC, frederikja163 commented on Parquet/ResultListener/ParquetResultListener.cs
> +        public static TraceSource Log { get; } = OpenTap.Log.CreateSource("Parquet");
```suggestion
        internal static TraceSource Log { get; } = OpenTap.Log.CreateSource("Parquet");
```

2024-03-22 08:41 UTC, rmadsen-ks requested changes
I don't understand how catching an error here will do what is written in issue #46.

Would it be possible to write a unit test that verifies the fix?

2024-03-22 09:22 UTC, frederikja163 commented
I added a unit test now. The problem is that if we throw an exception while writing the cache the stream and writer will not be disposed. Leaving them to always make errors on subsequent plan runs

2024-03-22 12:27 UTC, rmadsen-ks approved these changes
Looks good!

2024-03-22 12:27 UTC, merged