39 Add step id to schema
opentap/Parquet pull request #51
Opened 2024-03-22 08:34 UTC by frederikja163

2024-03-22 09:01 UTC, rmadsen-ks requested changes
Could we add to the unit test, that we verify that the step id is actually added? Maybe we could also test that the step id actually corresponds to the right step.

2024-03-22 09:23 UTC, frederikja163 commented on Parquet.Tests/ParquetFileTests.cs
> +                Assert.That(columns2.Skip(3).First().Data.GetValue(0)?.ToString(), Is.EqualTo(stepGuid.ToString()));
We have a test here that the step is actually added. But we can try doing it in a whole plan run too, if that is what you are talking about.

2024-03-22 10:05 UTC, frederikja163 commented
The tests fail right now, but once #47 has been merged it should fix the tests

2024-04-05 14:46 UTC, rmadsen-ks approved these changes
Looks good!

2024-04-05 14:46 UTC, merged